## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [6]:
X_boston=datasets.load_boston().data
y_boston=datasets.load_boston().target

X_train_boston,X_test_boston,y_train_boston,y_test_boston = train_test_split(X_boston,y_boston,test_size=0.2, random_state=4)

reg_Lasso = linear_model.Lasso(alpha=1.0)

reg_Lasso.fit(X_train_boston,y_train_boston)

y_pred=reg_Lasso.predict(X_test_boston)

In [7]:
reg_Lasso.coef_

array([-0.06494981,  0.04581458, -0.        ,  0.        , -0.        ,
        1.18140024,  0.01109101, -0.73695809,  0.23350042, -0.01551065,
       -0.69270805,  0.00763157, -0.6927848 ])

In [8]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test_boston, y_pred))

Mean squared error: 28.95


In [17]:
bri_reg=linear_model.Ridge(alpha=1.0)
bri_reg.fit(X_train_boston,y_train_boston)
y_pred_boston_bri=bri_reg.predict(X_test_boston)

In [18]:
bri_reg.coef_

array([-1.12499445e-01,  4.79562332e-02, -2.40438147e-02,  2.96199458e+00,
       -9.33966118e+00,  3.93079015e+00, -1.73821202e-02, -1.43347691e+00,
        2.75239392e-01, -1.38920708e-02, -8.31116943e-01,  9.15637729e-03,
       -4.66460539e-01])

In [19]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test_boston, y_pred_boston_bri))

Mean squared error: 25.74


In [10]:
X_linnerud=datasets.load_linnerud().data
y_linnerud=datasets.load_linnerud().target

X_train_linnerud,X_test_linnerud,y_train_linnerud,y_test_linnerud = train_test_split(X_linnerud,y_linnerud,test_size=0.2, random_state=4)

reg_Lasso_linnerud = linear_model.Lasso(alpha=1.0)

reg_Lasso_linnerud.fit(X_train_linnerud,y_train_linnerud)

y_pred_linnerud=reg_Lasso_linnerud.predict(X_test_linnerud)

In [11]:
reg_Lasso_linnerud.coef_

array([[-1.21702413, -0.18301572,  0.07085454],
       [-0.16500267, -0.04240416,  0.02848377],
       [ 0.10302969,  0.05543243, -0.03005608]])

In [12]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test_linnerud, y_pred_linnerud))

Mean squared error: 382.88


In [13]:
bri_reg=linear_model.Ridge(alpha=1.0)
bri_reg.fit(X_train_linnerud,y_train_linnerud)
y_pred_linnerud_bri=bri_reg.predict(X_test_linnerud)

In [14]:
bri_reg.coef_

array([[-1.28169016, -0.18036401,  0.072403  ],
       [-0.23446277, -0.03950683,  0.03008403],
       [ 0.17278069,  0.05251903, -0.03165848]])

In [15]:
print("Mean squared error: %.2f"
      % mean_squared_error(y_test_linnerud, y_pred_linnerud_bri))

Mean squared error: 385.93
